from fetch_stats import *
from utils import *
from email_send import *


config_dict = read_config('config.yaml')

from_email = config_dict['FROM_EMAIL']
to_email = config_dict['TO_EMAIL']
server = config_dict['SMTP']['host']
user_name = config_dict['SMTP']['username']
password = config_dict['SMTP']['password']

subject = "Windows server Running Summary"

stats = fetch_space()


html_code =  f""" <html>
     <head></head>
     <body>
     <br>
     <br>
     <h3> Disk Space Stats </h3><br>
     <b> Total space: </b> {stats['space']['total_space']} GB</br>
     <b> Used space: </b> {stats['space']['used_space']} GB</br>
     <b> Free space: </b> {stats['space']['free_space']} GB </br>
     <b> Mounted drives: </b> {','.join(stats['mounts'])}

     <br>
     <br>
     <h3> Battery Stats </h3>
     <b> Battery Percent: </b> {stats['battery']['percent']} %</br>
     <b> Is charger plugged?: </b> {stats['battery']['is_plugged']}</br>
"""

text = "This is autogenerated mail regarding windows running stats.Please take necessery action"

mailer = Email(from_email,to_email,
                subject,html_code,text,server)

try:
    mailer.send_mail(user_name,password)
except Exception as e:
    raise e



